sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t subinsebastian/learn-udemy-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true subinsebastian/learn-udemy-ci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learn-udemy-ci"
  env: "Learnudemyci-env"
  bucket_name: "elasticbeanstalk-us-east-2-115841269522"
  bucket_path: "learn-udemy-ci"

  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
