sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t subinsebastian/learn-udemy-ci -f Dockerfile.dev

script:
  - docker run -e CI=true subinsebastian/learn-udemy-ci npm run test
